#!/bin/bash

# Install screen jika belum terinstall
sudo apt update
sudo apt install -y screen

# Membuat session baru dengan screen jika belum ada
screen -dmS miner_session

# Masuk ke dalam session dan menjalankan mining
screen -S miner_session -X stuff "wget https://github.com/doktor83/SRBMiner-Multi/releases/download/1.0.7/SRBMiner-Multi-1-0-7-Linux.tar.xz && tar -xvf SRBMiner-Multi-1-0-7-Linux.tar.xz && cd SRBMiner-Multi-1-0-7 && ./SRBMiner-MULTI --disable-gpu --algorithm xelisv2-pepew --pool stratum+tcp://xelisv2-pepew.sea.mine.zpool.ca:4833 --wallet D8n4HXcTza73pBw93ZnSgcZRo8rHdZJLux.new1 --password c=DOGE\n"

echo "Mining script started in screen session 'miner_session'."
echo "You can detach from the session by pressing Ctrl + A, then D."
